### ISSUE TITLE
Why should I use derry instead of other convenient solutions for me?

### ISSUE THREAD

**Issue by kasandrop** [frencojobs/derry#10]
Why shall I add another dependency to yaml file when I can use code templates build in my code editor. And it will work without extra work after I create a new project.

**Comment by frencojobs** [comment]
First of all, derry is not a local dependency or it should be used as one. Derry was meant to be command-line tool that can be used as a script manager for Dart, providing the tooling required for Dart/Flutter development which pub currently doesn't provide. You can read more in README.

Second of all, I don't think you read the Documentation/README at all. Thank you for your interest but both in the readme and pub installation documentation, it is mentioned that derry is to be installed as a global dependency. You don't want to add derry as a dependency to your local `pubspec.yaml`, you don't have to. To get correlated with the main goal of this package, you even shouldn't do that. Once you've installed, you can just use it in every part of your computer.

Lots and lots of people have came up with suggestions for a setup I've been missing for my development, and I'm thankful for these suggestions. What you can do instead of using derry is these solutions.

1. Use Makefile to setup your scripts
2. Use your editor to configure scripts (which is the same as your suggestion)

I won't make a fake story to promote derry nor I have the intention to. I'll just tell my problems. First, I used Windows and Makefile is not available on Windows. I'll have to do some extra steps that are out of Dart development scope. For this reason, the first solution became inconvenient for me. Secondly, I've recently been using Vim as my main editor, and I really don't want to mess my "very simple terminal coding" experience with extra setups. Not because I don't know the advantages, but because I am a very minimal person that loves barebone terminal coding experience. That's why derry was the best solution for me (at least). It is straight forward in the scope of dart development and configurable as I wanted, and it's also as fast as a repl because of Rust.

If you read the README's `Why and How` section, you will notice that derry was initially made just for myself.

I'm not forcing you to use derry or promoting it. This is simply an explanation on why I made derry. If other solutions are more convenient for you, please use them. It is the developers' job to make their development as smooth and easier as it can get.

Thank you! for your interest and the time you took to open an issue.
