### ISSUE TITLE
Problem with bash linux terminal after running derry

### ISSUE THREAD

**Issue by maboumra** [frencojobs/derry#12]
Hi,

I use Linux Ubuntu and vscode to develop. When tested Derry everything seemed fine but, after I used Ctrl-C to stop a watch script, using build_runner to generate code, it broke the terminal and "Enter" becomes  ^M and I have to restart the terminal. Without derry I don't have this issue. Below is  my configuration:

derry.yaml
`watch: flutter pub run build_runner watch --delete-conflicting-outputs`

Great tool by the way. Hope you can help me.

**Comment by frencojobs** [comment]
SuperShell on Windows also have the same problem. On SuperShell, continuous typing of lots of <kbd>Ctrl+C</kbd> will save the day when typing only one <kbd>Ctrl+C</kbd> and entering or typing other words will literally break the terminal. I'm sure the same thing is happening on bash. I haven't had a chance to confirm but I'm sure the error will also appear on Mac.

I've concluded that the error is from Rust because I've tested on a separate Rust program and found the exact error. I don't know exactly but the culprit might be the process that is not killed properly when the parent program has stopped. I'm sorry for the issue. I'm still looking for a solution to implement that process in the best way. Meanwhile, continuous <kbd>Ctrl+C</kbd>s will probably save your day too.

Thank you for taking time to open the issue. I'll try to come up with a solution as fast as I can as this is a very severe issue.
> Great tool by the way.

Thank you for that too 😊.

**Comment by frencojobs** [comment]
@maboumra bugfix/ctrl-c branch contains the fix. I've tested it on PowerShell and the problem seems to be fixed. Since I don't have Ubuntu available to test, can you please help check if the fix is working or not?

You can clone the repo and the example folder contains a derry config file with watch script setup. The following command can be used to test with local derry build.
```bash
pub run derry run watch # not derry run watch
```

**Comment by frencojobs** [comment]
So anyway, I just tested it myself on Ubuntu 20 with VirtualBox, and the issue seems to be fixed by the commit. I'll release the fix on v0.0.8.

**Comment by maboumra** [comment]
Great job. Thank you!
