### ISSUE TITLE
Allow additional params in subcommands

### ISSUE THREAD

**Issue by jamesblasco** [frencojobs/derry#13]
First, Thanks for the amazing library. It has already saved me a lot of time.

Right now it is possible to add additional params and subcommand, but not both together.
I would like to do something like this
```yaml
force-build: $build -- --delete-conflicting-outputs
```

**Comment by frencojobs** [comment]
Wow! This indeed can be a very useful API for some use cases. I'll implement it as soon as the current bugs are fixed. Thank you for the idea. By the way, this issue made me notice the #14 issue and fix it.
> Thanks for the amazing library.

Thank you 😊. I'm thankful that people are actually using it.

**Comment by frencojobs** [comment]
I was just analyzing the idea today, and realized what you need is not additional parameters but they might be just parameters. I used additional parameters to separate them from the parameters that apply to the current command. They go deep down to the core of execution.
```bash
derry build --silent -- --delete-conflicting-outputs
```
In this example, I used additional parameters to separate them from the default `--silent` parameter. The `silent` option applies to the build command while the `delete-conflicting-outputs` don't. It only applies to whatever command the build config is pointing to.

In your example, the subcommands are just pointers. They point to a specific command and that's the only thing they do.
```yaml
build: pub run build_runner build

force-build: $build -- --delete-conflicting-outputs
# is the same as
force-build: pub run build runner build -- --delete-conflicting-outputs
```
Did you see that? That's why I said you might need parameters and not additional ones. They might just be like this.
```yaml
force-build: $build --delete-conflicting-outputs
```
Either way, I'm just trying to see what's the intended idea is. The feature is not yet implemented. The example won't even work, because the whole string is replaced when a dollar sign is prefixed. (Yeah, I know I should have used Regex.) 

Is my correction as you intended the API to look like? If so, I'll start implementing it soon.

**Comment by jamesblasco** [comment]
Yeah, that could work for me. Thanks for the extensive explanation!

**Comment by frencojobs** [comment]
Derry v0.0.9 will have this feature. Thanks for suggestion and have a nice day 🤗 .

**Comment by jamesblasco** [comment]
Thank you soo much for this! Have a great day for you too.
