### ISSUE TITLE
Add description for listing commands

### ISSUE THREAD

**Issue by JagandeepBrar** [frencojobs/derry#46]
Hello, really love derry!

It would be really awesome if you could add support for adding a description to the script when using `derry ls`.

I think an easy/clean way would be to use the syntax used for execution type, with a `(description)` field:

```yaml
build:
  (description): Run build_runner to generate Dart files # --> this line
  (execution): once # multiple by default
  (scripts):
    - cat generated.txt
    - pub run build_runner build # won't be called if generated.txt does not exist
```

I use derry in an open-source Flutter project, so adding in descriptions for users to know what the scripts do would be really convenient

**Comment by frencojobs** [comment]
Hi :wave:! Thanks a lot for the suggestion. I have added the feature in v1.4.1 and it should be available by now. But because I didn't want to poise the output of `derry ls`, I have instead added another option `-d` which should print the list with descriptions.

```sh
derry ls -d
```

Again, thanks a lot for filing the issue and (also kind words). I'm glad you liked derry. Sorry for the delay for I have not been doing much since the coup d'état.
